In [1]:
import numpy as np

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [5]:
negs = len(a[a<0])
pos = len(a[a>0])

In [7]:
print(f'there are {pos} positives, and {negs} negatives')

there are 5 positives, and 4 negatives


## Find how many positive numbers that are even

In [9]:
positives = a[a>0]

In [10]:
pande = positives[positives%2 == 0]

In [12]:
len(pande)

3

## If you were to add 3 to each number, how many positive numbers would there be?

In [13]:
ap3 = a+3 

In [14]:
len(ap3[ap3 > 0])

10

In [15]:
(a**2).std()

144.0243035046516

In [16]:
center_a = a - a.mean()

In [17]:
center_a

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [18]:
z = center_a/a.std()

In [19]:
z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [20]:
a<0

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])